### ISSUE TITLE
Release mode uses unsupported shader model

### ISSUE THREAD

**Issue by florianschut** [TeamWisp/Procedural-Ray-Tracing#103]
**Describe the bug**
On my last gen 980m I can't run the latest shader model. In debug it works fine as it goes down to a previous shader model however when running in release the demo crashes as the shader model used isn't supported.

**To Reproduce**
Set Solution configuration to Release on a 980m and run the demo

**Expected behaviour**
The program will assert and give a DX error message in the output exclaming the shader model is not supported.

**Screenshots**

**Desktop (please complete the following information):**
 - Hardware CPU:6700HQ, GPU:GTX 980m, RAM:32GB]

**Additional context**

**Comment by VZout** [comment]
Is it possible that you're trying to run it with the integrated GPU which doesn't support the latest shader model?

**Comment by VZout** [comment]
spellings control changed reconfigure to deconfiture. 👍

**Comment by VZout** [comment]
Closing for now. Seems to be not a issue.
