### ISSUE TITLE
Skybox rotated 90 degrees

### ISSUE THREAD

**Issue by MeineZ** [TeamWisp/Procedural-Ray-Tracing#135]
**Description*
The skybox in 2 renderers is rotated 90 degrees from the third renderer. Not sure which one is the correct one. This might be caused by the different coordinate systems.

**To Reproduce**
1. Look at the skybox.
2. Switch between frame graphs (F2).

**Expected behavior**
The skybox should be displayed like it is in every other frame graph.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Not relevant
 - Hardware: Not relevant

**Comment by florianschut** [comment]
Fixed in PR #149
