### ISSUE TITLE
Framebuffer resize on resize

### ISSUE THREAD

**Issue by MeineZ** [TeamWisp/Procedural-Ray-Tracing#136]
**Describe the bug**
Only the current frame graph resizes the framebuffers on resize. The others will not be resized.

**To Reproduce**
1. Resize the window
2. Switch frame graph (F2)

**Expected behavior**
All framebuffers should be resized.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Not relevant
 - Hardware: Not relevant

**Comment by florianschut** [comment]
Should be solved with PR #152
