### ISSUE TITLE
LightNode contains temporary variable.

### ISSUE THREAD

**Issue by VZout** [TeamWisp/Procedural-Ray-Tracing#137]
The light_node contains `Light m_temp`. This is quite ugly code especially if you look at where its used.

**Comment by Nielsbishere** [comment]
Whenever a LightNode is added, it isn't allocated into an array yet. To fix this, you modify a Light*, which points to m_temp at the start. When it's allocated, it modifies it directly into the light array. This does mean that every LightNode has a Light and Light*, but also means that there's no heap allocation. It is an intermediate that will only be used for initialization (aka before it receives an allocated light).
