### ISSUE TITLE
Improper program behaviour when shutting down

### ISSUE THREAD

**Issue by 161563** [TeamWisp/Procedural-Ray-Tracing#169]
**Describe the bug**
The program crashes when shut down while running in DEBUG, returning code 3 instead of 0 and giving the following error:
`
Debug Assertion Failed!
Program: ...cedural-Ray-Tracing\build_vs2017_win64\bin\Debug\WispDemo.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 908
Expression: is_block_type_valid(header->_block_use)
For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
`
**To Reproduce**
1. Run the project
2. Click the close button
3. See error

**Expected behavior**
The program should shut down properly, returning code 0.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1809
 - Hardware CPU: 6700HQ, GPU: GTX 970M, RAM: 16GB (Koen)
 - Hardware CPU: 6700HQ, GPU: GTX 980M, RAM: 32GB (Florian Laptop)
 - Hardware CPU: 8700K,    GPU: GTX 1080, RAM: 16GB (Florian Desktop)

**Comment by florianschut** [comment]
### Fix proposed in #175 
The issue was caused by deleting an ID3D12Resource instead of releasing it. Crash prevented, resource cleaned up 👌
