### ISSUE TITLE
Texture pool causes crash on application shutdown

### ISSUE THREAD

**Issue by 161563** [TeamWisp/Procedural-Ray-Tracing#178]
**Describe the bug**
When closing the application, when the texture pool gets destroyed a read access violation (location: 0xFFFFFFFFFFFFFFFF) is thrown in the GetFrameIdx function.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the application
2. Close it after initialization is finished
3. See error

**Expected behaviour**
The application should shut down without any errors.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1809
 - Hardware [e.g. CPU:6700HQ, GPU:GTX 970M, RAM:16GB]

**Comment by LaisoEmilio** [comment]
Fixed.
