### ISSUE TITLE
Deferred Composition uses A RGB8 render target format

### ISSUE THREAD

**Issue by VZout** [TeamWisp/Procedural-Ray-Tracing#188]
**Describe the bug**
The deferred composition task uses a RGB8 render target. This is not what we want for HDR support.

**To Reproduce**
`d3d12_deferred_composition.hpp/cpp`

**Expected behaviour**
We want the buffer to be 32RGB so we can output it as hdr after post processing.

**Comment by florianschut** [comment]
No longer the case since #225
