### ISSUE TITLE
Starting Engine on non-deferred

### ISSUE THREAD

**Issue by LaisoEmilio** [TeamWisp/Procedural-Ray-Tracing#190]
**Describe the bug**
Starting the renderer on RT_HYBRID or FULL_RAYTRACING pipelines instead of DEFERRED, makes the engine crash.

**To Reproduce**
1. Go to demo_frame_graphs.hpp
2. Change this line
```
static PrebuildFrameGraph current = fg_manager::PrebuildFrameGraph::DEFERRED;
```
Into
```
static PrebuildFrameGraph current = fg_manager::PrebuildFrameGraph::RT_HYBRID;
```
3. Watch it crash.

**Expected behaviour**
The engine should just run normally and render using the desired pipeline.

**Screenshots**
None.

**Comment by VZout** [comment]
Fixed! 
https://github.com/TeamWisp/Procedural-Ray-Tracing/pull/207/files
