### ISSUE TITLE
Frame graph redesign.

### ISSUE THREAD

**Issue by VZout** [TeamWisp/Procedural-Ray-Tracing#30]
The current frame graph implementation is relatively fast. But lacks the possibility for a lot of optimization.
The redesign I propose is re-implementing it using standard object oriented programming. This would allow for more template magic and constexpr functionality. This design should be bench marked against the current implementation though.

**Comment by Nielsbishere** [comment]
Current implementation relies too much on std::function. Most CPU time is spent in std::function::operator(), this could be improved through using regular pointers or finding a replacement for std::function.
