### ISSUE TITLE
All function definitions don't follow the style guide of the `t_` prefix.

### ISSUE THREAD

**Issue by VZout** [TeamWisp/Procedural-Ray-Tracing#31]
Either the style guide or the code should be refactored. Most likely this will be solved using a poll.

**Comment by MeineZ** [comment]
Has already been voted for. 
Conclusion: `t_` must be removed from the style guide.

**Comment by MeineZ** [comment]
Created a new [pull request](https://github.com/TeamWisp/TeamWisp.github.io/pull/2) in the website repository. I have removed all `t_`'s from the function arguments in the project.
