### ISSUE TITLE
SceneGraph: Node update

### ISSUE THREAD

**Issue by Nielsbishere** [TeamWisp/Procedural-Ray-Tracing#65]
The current implementation of parenting (in feature_sg_parenting), relies heavily on which nodes are updated first (parent's transform). This means that the current system of nodes updating (grouping them by type, rather than dependency) is not valid anymore. If a camera is linked to a MeshNode, the mesh node will always be updated after the camera. This causes jitters. I'd recommend updating all nodes by dependency, not type.

**Comment by VZout** [comment]
Updating of the constant buffers shouldn't be done by the type based loops indeed. Those should be prepacked by a scene graph update that start from the root node and goes down its children.

**Comment by Nielsbishere** [comment]
Fixed in feature_sg_parenting; node transforms are updated separately and starting from the root node (only going down a node if their transform has been modified).
