### ISSUE TITLE
ResizeBuffers doesn't consistently get called by transitioning to full screen

### ISSUE THREAD

**Issue by florianschut** [TeamWisp/Procedural-Ray-Tracing#67]
DXGI ERROR: IDXGISwapChain::Present: The application has not called ResizeBuffers or re-created the SwapChain after a fullscreen or windowed transition. Flip model swapchains (DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL and DXGI_SWAP_EFFECT_FLIP_DISCARD) are required to do so. [ MISCELLANEOUS ERROR #117: ]

**Comment by VZout** [comment]
Fixed? Closing for now
