### ISSUE TITLE
Aliasing issues when using SampleLevel in compute shaders

### ISSUE THREAD

**Issue by 161563** [TeamWisp/Procedural-Ray-Tracing#75]
When using SampleLevel instead of the [] operator in the compute shader for deferred compostion weird aliasing effects happen.
![aliasing effects](https://user-images.githubusercontent.com/40601547/49731498-d9336080-fc7b-11e8-896d-ed70f810b12e.PNG)

**Comment by VZout** [comment]
believe this is fixed.
